$(document).ready(function(){
	
	var config = {
	    siteURL: 'http://www.baldatee.com/', // Change this to your site
		searchSite	: true,
		type		: 'web',
		append		: false,
		perPage		: 8,			// A maximum of 8 is allowed by Google
		page		: 0				// The start page
	}
	
	// The small arrow that marks the active search icon:
	var arrow = $('<span>',{className:'arrow'}).appendTo('ul.icons');
	
	$('ul.icons li').click(function(){
		var el = $(this);
		
		if(el.hasClass('active')){
			// The icon is already active, exit
			return false;
		}
		
		el.siblings().removeClass('active');
		el.addClass('active');
		
		// Move the arrow below this icon
		arrow.stop().animate({
			left		: el.position().left,
			marginLeft	: (el.width()/2)-4
		});
		
		// Set the search type
		config.type = el.attr('data-searchType');
		$('#more').fadeOut();
	});
	
	// Adding the site domain as a label for the first radio button:
	$('#siteNameLabel').append(' '+config.siteURL);
	
	// Marking the Search tutorialzine.com radio as active:
	$('#searchSite').click();	
	
	// Marking the web search icon as active:
	$('li.web').click();
	
	// Focusing the input text box:
	$('#s').focus();

	$('#searchForm').click(function () {
		googleSearch();
		return false;
	});
	
	$('#searchSite,#searchWeb').change(function(){
		// Listening for a click on one of the radio buttons.
		// config.searchSite is either true or false.
		
		config.searchSite = this.id == 'searchSite';
	});
	
	
	function googleSearch(settings){
		
		// If no parameters are supplied to the function,
		// it takes its defaults from the config object above:
		
		settings = $.extend({},config,settings);
		settings.term = settings.term || $('#s').val();
		
		if(settings.searchSite){
			// Using the Google site:example.com to limit the search to a
			// specific domain:
			settings.term = 'site:'+settings.siteURL+' '+settings.term;
		}
		
		// URL of Google's AJAX search API
		var apiURL = 'http://ajax.googleapis.com/ajax/services/search/'+settings.type+'?v=1.0&callback=?';
		var resultsDiv = $('#resultsDiv');
		
		$.getJSON(apiURL,{q:settings.term,rsz:settings.perPage,start:settings.page*settings.perPage},function(r){
			
			var results = r.responseData.results;
			$('#more').remove();
			
			if(results.length){
				
				// If results were returned, add them to a pageContainer div,
				// after which append them to the #resultsDiv:
				
				var pageContainer = $('<div>',{className:'pageContainer'});
				
				for(var i=0;i<results.length;i++){
					// Creating a new result object and firing its toString method:
					pageContainer.append(new result(results[i]) + '');
				}
				
				if(!settings.append){
					// This is executed when running a new search, 
					// instead of clicking on the More button:
					resultsDiv.empty();
				}
				
				pageContainer.append('<div class="clear"></div>')
							 .hide().appendTo(resultsDiv)
							 .fadeIn('slow');
				
				var cursor = r.responseData.cursor;
				
				// Checking if there are more pages with results, 
				// and deciding whether to show the More button:
				
				if( +cursor.estimatedResultCount > (settings.page+1)*settings.perPage){
					$('<div>',{id:'more'}).appendTo(resultsDiv).click(function(){
						googleSearch({append:true,page:settings.page+1});
						$(this).fadeOut();
					});
				}
			}
			else {
				
				// No results were found for this search.
				
				resultsDiv.empty();
				$('<p>',{className:'notFound',html:'No Results Were Found!'}).hide().appendTo(resultsDiv).fadeIn();
			}
		});
	}
	
	function result(r){
		
		// This is class definition. Object of this class are created for
		// each result. The markup is generated by the .toString() method.
		
		var arr = [];
		
		// GsearchResultClass is passed by the google API
		switch(r.GsearchResultClass){

			case 'GwebSearch':
				arr = [
					'<div class="webResult">',
					'<h2><a href="',r.unescapedUrl,'" target="_blank">',r.title,'</a></h2>',
					'<p>',r.content,'</p>',
					'<a href="',r.unescapedUrl,'" target="_blank">',r.visibleUrl,'</a>',
					'</div>'
				];
			break;
			case 'GimageSearch':
				arr = [
					'<div class="imageResult">',
					'<a target="_blank" href="',r.unescapedUrl,'" title="',r.titleNoFormatting,'" class="pic" style="width:',r.tbWidth,'px;height:',r.tbHeight,'px;">',
					'<img src="',r.tbUrl,'" width="',r.tbWidth,'" height="',r.tbHeight,'" /></a>',
					'<div class="clear"></div>','<a href="',r.originalContextUrl,'" target="_blank">',r.visibleUrl,'</a>',
					'</div>'
				];
			break;
			case 'GvideoSearch':
				arr = [
					'<div class="imageResult">',
					'<a target="_blank" href="',r.url,'" title="',r.titleNoFormatting,'" class="pic" style="width:150px;height:auto;">',
					'<img src="',r.tbUrl,'" width="100%" /></a>',
					'<div class="clear"></div>','<a href="',r.originalContextUrl,'" target="_blank">',r.publisher,'</a>',
					'</div>'
				];
			break;
			case 'GnewsSearch':
				arr = [
					'<div class="webResult">',
					'<h2><a href="',r.unescapedUrl,'" target="_blank">',r.title,'</a></h2>',
					'<p>',r.content,'</p>',
					'<a href="',r.unescapedUrl,'" target="_blank">',r.publisher,'</a>',
					'</div>'
				];
			break;
		}
		
		// The toString method.
		this.toString = function(){
			return arr.join('');
		}
	}
	
	
});    
    $(window).load(function () {
        //jQuery('#loading-image').hide();
        //ShowMargins();
        $(".imgEvent").each(function () {
            var imagewidth = $(this).width();
            var maxsize = 700;
            if (imagewidth > maxsize)
                $(this).animate({ width: maxsize });
        });
    });
function ShowMargins() {
    // put all your jQuery goodness in here.
    var hleft = $("#box1").height();
    var hright = $("#box2").height();

    if (hleft > hright) {
        $("#box2").css('height', hleft);
    }
    else {
        $("#box1").css('height', hright);
    }
}
$(window).load(function () {
    //jQuery('#loading-image').hide();
    ShowMargins();
});
    function clearText2() {
        $("#s").val('');
        $("#s").css('font-style', 'normal');
        $("#s").css('color', 'black');
    }
function resetText2() {
    if ($("#s").val() == "") {
        $("#s").val('');
        $("#s").val('ÅÈÍË');
        $("#s").css('font-style', 'italic');
        $("#s").css('color', 'gray');
    }
}
    function ImageSize(imageid) {

        var imagewidth = $("#" + imageid).width();
        var maxsize = 750;
        if (imagewidth > maxsize)
            $("#" + imageid).css('width', maxsize);

    }
function validateForm() {
    var x = document.forms["myForm"]["mail"].value;
    var atpos = x.indexOf("@");
    var dotpos = x.lastIndexOf(".");
    if (atpos < 1 || dotpos < atpos + 2 || dotpos + 2 >= x.length) {
        alert("Not a valid e-mail address");
        return false;
    }
}
    function SetSource(id, name, catId) {

        name = name.substring(0, name.lastIndexOf(','));
        var images = name.split(', ');
        var source = '';
        var options = '';

        for (var i = 0; i < Math.min(images.length, 1); i++) {
            source = 'Admin/Uploads/Events/' + id + '/' + images[i];
            if (images[i] != undefined && images != '') {
                options += '<img id="' + id + '_' + i + '" alt="" src="' + source + '" width="110px" height="80px" />&nbsp;';
            }
        }

        $('#divImages' + catId + '_' + id).html(options);
    }
function SetDescription(id, desc) {
    $('#Description_' + id).html(desc.substring(0, Math.min(desc.length, 100)) + '...');
}
function SetHomeAd(id, name, catId, width, height, profileImage, style) {

    var options = '';

    if (profileImage != '' && profileImage != null && profileImage != " ") {
        source = 'Admin/Uploads/Events/Profile/' + id + '/' + profileImage;
        options += '<a href="HomeAdDetail.aspx?id=' + id + '" target="_blank">';
        options += '<img alt="" src="' + source + '" width="' + width + '" height="' + height + '" style="' + style + '" /></a>';
    }
    else {
        name = name.substring(0, name.lastIndexOf(','));
        var images = name.split(', ');
        var source = '';

        for (var i = 0; i < Math.min(images.length, 1); i++) {
            source = 'Admin/Uploads/Events/' + id + '/' + images[i];
            if (images[i] != undefined && images != '') {
                options += '<a href="HomeAdDetail.aspx?id=' + id + '">'
                options += '<img id="' + id + '_' + i + '" alt="" src="' + source + '" width="' + width + '" height="' + height + '" style="border:1px solid black;" />&nbsp;';
                options += '</a>';
            }
        }
    }

    $('#divImages' + catId + '_' + id).html(options);
}
function SetHomeAdT(id, name, catId, width, height, profileImage, style) {

    var options = '';

    if (profileImage != '' && profileImage != null && profileImage != " ") {
        source = 'Admin/Uploads/Events/Profile/' + id + '/' + profileImage;
        options += '<a href="EventDetail.aspx?id=' + id + '" target="_blank">';
        options += '<img alt="" src="' + source + '" width="' + width + '" height="' + height + '" style="' + style + '" /></a>';
    }
    else {
        name = name.substring(0, name.lastIndexOf(','));
        var images = name.split(', ');
        var source = '';

        for (var i = 0; i < Math.min(images.length, 1); i++) {
            source = 'Admin/Uploads/Events/' + id + '/' + images[i];
            if (images[i] != undefined && images != '') {
                options += '<a href="EventDetail.aspx?id=' + id + '">'
                options += '<img id="' + id + '_' + i + '" alt="" src="' + source + '" width="' + width + '" height="' + height + '" style="border:1px solid black;" />&nbsp;';
                options += '</a>';
            }
        }
    }

    $('#divImages' + catId + '_' + id).html(options);
}
function SetSourceTab(id, name, catId) {

    name = name.substring(0, name.lastIndexOf(','));
    var images = name.split(', ');
    var source = '';
    var options = '';

    for (var i = 0; i < Math.min(images.length, 1); i++) {
        source = 'Admin/Uploads/Events/' + id + '/' + images[i];
        if (images[i] != undefined && images != '') {
            options += '<img id="' + id + '_' + i + '" alt="" src="' + source + '" width="210px" height="180px" />&nbsp;';
        }
    }

    $('#divImages' + catId + '_' + id).html(options);
}
    var time = new Date().getTime();
$(document.body).bind("mousemove keypress", function(e) {
    time = new Date().getTime();
});
    function increaseFontSize() {
        var size = $('#wrapper_Content').css("font-size");
        size = size.replace("px", "");
        size++; size++; size++;
        $('#wrapper_Content').css("font-size", size + "px");
        $('#wrapper_Content').find('*').css("font-size", size + "px");
        if (size >= "18" && size < "30")
            $('#wrapper_Content').find('*').css("line-height", "28px");
        else if (size >= "30")
            $('#wrapper_Content').find('*').css("line-height", "44px");
    }
function decreaseFontSize() {
    var size = $('#wrapper_Content').css("font-size");
    size = size.replace("px", "");
    size--; size--; size--;
    $('#wrapper_Content').css("font-size", size + "px");
    $('#wrapper_Content').find('*').css("font-size", size + "px");
    if (size >= "30")
        $('#wrapper_Content').find('*').css("line-height", "44px");
    else
        $('#wrapper_Content').find('*').css("line-height", "28px");
}
    function resizeIframe(obj) {
        obj.style.height = obj.contentWindow.document.body.scrollHeight + 'px';
    }